version: '3'
services:

  brc20query:
    build: .
    image: brc20query:v1.0
    volumes:
      - ./data:/data/data
    ports:
      - "5555:8000"
    restart: always
    environment:
      LISTEN: 0.0.0.0:8000
      BASE_PATH: ""
      BRC20_PROCESS_AFTER_HEIGHT: 767400
      BRC20_PROCESS_BEFORE_HEIGHT: 824478
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_DATABASE: "brc20swap"
      DB_USER: "postgres"
      DB_PASSWD: "xxxxxx"
      DB_BRC20PROTOCOL_HOST: postgres
      DB_BRC20PROTOCOL_PORT: 5432
      DB_BRC20PROTOCOL_DATABASE: brc20
      DB_BRC20PROTOCOL_USER: postgres
      DB_BRC20PROTOCOL_PASSWD: "xxxxxx"
      DB_METAPROTOCOL_HOST: postgres
      DB_METAPROTOCOL_PORT: 5432
      DB_METAPROTOCOL_DATABASE: postgres
      DB_METAPROTOCOL_USER: postgres
      DB_METAPROTOCOL_PASSWD: "xxxxxx"

    labels:
      - "name=brc20query"
    logging:
      driver: "json-file"
      options:
        labels: "name"
        max-size: "1g"
        max-file: "3"
