[book]
title = "Ordinal Theory Handbook"
authors = ["Casey Rodarmor", "Raph Japh"]
language = "en"
src = "src"

[build]
build-dir = "build"
create-missing = false
extra-watch-dirs = ["po"]

[output.html]
cname = "docs.ordinals.com"
default-theme = "coal"
git-repository-url = "https://github.com/ordinals/ord"
preferred-dark-theme = "coal"
additional-css = ["index.css"]

[output.linkcheck]

[preprocessor.gettext]
after = ["links"]
