// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import "os"

var basePath = os.Getenv("BASE_PATH")

func init() {
	SwaggerInfo.BasePath = basePath
}
