drop table if exists ord_transfers;
drop table if exists ord_number_to_id;
drop table if exists ord_content;
drop table if exists block_hashes;
drop table if exists ord_indexer_reorg_stats;
drop table if exists ord_indexer_work_stats;
drop table if exists ord_indexer_version;
drop table if exists ord_network_type;
drop table if exists ord_transfer_counts;